### ISSUE TITLE
MiniSearch serialization format will change in the next major release

### ISSUE THREAD

**Issue by lucaong** [seppo0010/minisearch-indexrs#1]
Hello @seppo0010 ,
thanks a lot for your library! I wanted to let you know that `MiniSearch` will soon change its serialization format in a backward-incompatible way, as part of the next major release. The reason is on one hand to enable some performance optimizations that made indexing much faster, on the other to decouple the serialization format from the internals of the radix tree implementation, allowing further optimizations to be added in the future without breaking serialization compatibility again.

You can read more about the motivation in [this thread](https://github.com/lucaong/minisearch/pull/122#issuecomment-1041318324).

The new format, resulting from the combination of [this PR](https://github.com/lucaong/minisearch/pull/124) and [this other PR](https://github.com/lucaong/minisearch/pull/122), will be actually simpler:

  - The type of `fieldLength` and `averageFieldLength` have changed: instead of using objects mapping `fieldId` to a number, they now use arrays (the array index corresponds to the `fieldId`, and the value is the length).
  - The `index` field is now an array of `[term, termData]` tuples, where `termData` is the indexing data stored in the leaves of the radix tree. Before, it used to contain the raw internal objects of the radix tree. This might make your library simpler, as it does not have to build the radix tree.
  - A new `serializationVersion` field was added, now with the integer value `1`, to make it possible in the future to detect the serialization format version, should it change again (I do not plan to change it though, unless strictly necessary).

I thought to let you know in advance, in case you are thinking to update your library to the new version.

**Comment by seppo0010** [comment]
Thanks! I don't think I will anyway.
